vscode:
  extensions:
    - Tobiah.unity-tools@1.1.1:BxAZIio1njang4v291eq1w==
    - craigthomas.supersharp@0.1.4:m8YWHqiDaPm1TguBm2/7BQ==
    - ms-vscode.csharp@1.21.7:63Epcq/w+Vl8tIwYMHyrXg==
    - kleber-swf.unity-code-snippets@1.3.0:20p0HMEO99isQTYP5Qq7kA==
    - eppz.eppz-code@1.2.41:6OTkOrze47tvJXSwxdKZbw==